version: "3"
services: 
  pg_db:
    image: postgres:10
    volumes: 
      - ./db:/var/lib/postgresql/data
    expose: 
      - 5432
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo